---
title: "Impact of fishing pressure on California Spiny Lobster abundance and community size structure along the Santa Barbara Coast"
author: "Shuhan Song"
date: "November 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#loading packages
library(tidyverse)
library(janitor)
library(tidyr)
library(DT)
library(plotly)

# read in csv file
lobster_abundance <- read_csv("lobster_abundance_sbc_lter.csv", na = "-99999") %>% 
  clean_names()
```

### Introduction

### Data and Methods

### Results  
#### A. Annual abundance of lobsters at each site

```{r}
mpa_site <- c("NAPL", "IVEE")

abdn_year_site <- lobster_abundance %>% 
  group_by(year, site) %>% 
  summarize(annual_abundance = sum(count)) %>% 
  mutate(mpa = ifelse(site %in% mpa_site, "MPA", "non-MPA")) %>% 
  mutate(year_abb = year - 2000)

ggplot(data = abdn_year_site, 
       aes(x = year_abb,
           y = annual_abundance)) +
  geom_line(aes(color = mpa)) +
  geom_point(aes(color = mpa),
             alpha = 0.5) +
  facet_wrap(~site) +
  labs(x = "Year", 
       y = "Annual abundance",
       color = "Site types") +
  theme_light()

```

_**Figure 1.**_ 


#### B. 

#### C. 

### Summary

### References

